name: Angular CI/CD (S2I - No Docker)

on:
  push:
    branches:
      - main

env:
  APP_NAME: s2i-angular
  NAMESPACE: poc-01-dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Generate tag
      - name: Generate Tag
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          COMMIT_HASH=$(git rev-parse --short HEAD)
          TAG=${BUILD_NUMBER}-${COMMIT_HASH}
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Install oc CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/
          oc version    

      # 3️⃣ Login to OpenShift
      - name: Login to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} \
            --token=${{ secrets.OPENSHIFT_TOKEN }} \
            --insecure-skip-tls-verify=true


      # 4️⃣ Switch project
      - name: Select Project
        run: |
          oc project $NAMESPACE

      # 5️⃣ Start S2I Build
      - name: Trigger Build
        run: |
          oc start-build $APP_NAME --follow

      # 6️⃣ Tag Image (buildNumber + commitHash)
      - name: Tag Image
        run: |
          oc tag $APP_NAME:latest $APP_NAME:$TAG

      # 7️⃣ Update Deployment to new tag
      - name: Deploy New Image
        run: |
          oc set image deployment/$APP_NAME \
            $APP_NAME=image-registry.openshift-image-registry.svc:5000/$NAMESPACE/$APP_NAME:$TAG

      # 8️⃣ Rollout restart (refresh route)
      - name: Restart Deployment
        run: |
          oc rollout restart deployment/$APP_NAME

      # 9️⃣ Wait for rollout
      - name: Verify Deployment
        run: |
          oc rollout status deployment/$APP_NAME